# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/mythical-bazaar-470812-n3/flask-repo/flask-app:v01', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/mythical-bazaar-470812-n3/flask-repo/flask-app:v01']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'flask-release-$SHORT_SHA'
      - '--delivery-pipeline=flask-pipeline'
      - '--region=us-central1'
      - '--images=flask-app=us-central1-docker.pkg.dev/mythical-bazaar-470812-n3/flask-repo/flask-app:v01'

images:
  - 'us-central1-docker.pkg.dev/mythical-bazaar-470812-n3/flask-repo/flask-app:v01'
