apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-pipeline
description: Pipeline to deploy Flask app to GKE
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment
gke:
  cluster: projects/mythical-bazaar-470812-n3/locations/us-central1-a/clusters/flask-cluster
  internalIp: false
